site_name: "Ams Shop"

data_source:
  type: "haystack"
  haystack:
    uri: "http://172.20.40.22"
    username: "AMS"
    password_env: "NIAGARA_PASSWORD"
    project: "default"

comfort:
  occupied_start: "07:00"
  occupied_end: "18:00"
  setpoint_column: "zn_sp"
  temp_column: "zn_t"
  timestamp_column: "timestamp"
  equip_column: "zone_root"
  comfort_band_degF: 2.0

mqtt:
  host: "localhost"
  port: 1883
  history_topic: "niagara/histories"
  equipment_topic: "niagara/equipment"

db_path: "data/history.sqlite"
db_retention_hours: 720
